<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<div id="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>이름</th>
				<th>이름</th>
				<th>이름</th>
				<th>이름</th>
				<th>이름</th>
				<th>이름</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>       
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
				<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			<tr>
				<td>제목1</td>
				<td>도서번호1</td>
				<td>ISBN1</td>
				<td>저자1</td>
				<td>출판사1</td>
				<td>등록날짜1</td>
			</tr>
			
		</tbody>
	</table>
</div>